---
Author: "Alex, Goajun, Sergey, Bastien"
---

<br>

###Background
We have performed analysis of electricity data provided by the French Distribution Network (RTE)

####Analysis
1. Comparison between supply and demand
2. Evolution of energy mix
3. Correlation between time of the day and solar energy production 
4. Correlation between time of the day and wind energy
5. Correlation between supply and demand vs. import/export
6. Correlation between consumption and weather

####Source

Open data: https://www.data.gouv.fr/fr/datasets/electricite-consommation-production-co2-et-echanges/

```{r eval=TRUE, echo=FALSE, comment=NA, warning=FALSE, message=FALSE,results='asis',fig.align='center', fig=TRUE}
DataSet<-read.csv("RTE - clean data 2012-2014 15-1-16.csv", header=TRUE)
```
The file has the following structure. It has `r nrow(DataSet)` rows and `r ncol(DataSet)` columns.

###Part I: Comparison between supply and demand
`r n<-16`
I am a `r n`J



###Part II: Evolution of energy mix

####??

###Part III: Correlation between time of the day and solar energy production

####??

###Part IV: Correlation between time of the day and wind energy (test Sergey)

####??

###Part V: Correlation between supply and demand vs. import/export (test Gaojun)

####??

###Part VI: Correlation between consumption and weather

Test for Alex
=======
#test de push by ALex

Test for Bastien 4:35pm
